name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  clear-docker-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear docker context
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop suivi-patient-front
            docker system prune -a -f

  deploy-patient-front:
    runs-on: ubuntu-latest
    needs: clear-docker-context
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: .
          target: suivi-patient-front

      - name: Build API Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /${{ secrets.SERVER_USERNAME }}/suivi-patient-front
            docker build -t suivi-patient-front .

      - name: Mount Landing page Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker run -d \
            --name=suivi-patient-front \
            -p 3000:3000 \
            --restart always \
            suivi-patient-front
